#默认激活的文件
spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#mybaits配置
server:
  port: 9070
url:
  tilePath: /data/data/tiledata
  tilePath2: /data/data/tiledata20_1
  tilePath3: /data/data/tiledata20_2
  tilePath4: /data/data/tiledata20_3
  tilePath5: /data/data/tiledata20_4
  notePath: /data/data
  earthC: 40075016.686
  cacheTilePath:
  imageNotePath:
  gdalCachPath: D:\data\cc\158\20231108

